name: CPP Docker image publish

trigger: none

parameters:
  - name: RUN_RELEASE
    type: boolean
    default: false

resources:
  repositories:
    - repository: cppAzureDevOpsTemplates
      type: github
      name: hmcts/cpp-azure-devops-templates
      endpoint: 'hmcts'
      ref: 'main'

pool:
  name: "MDV-ADO-AGENT-AKS-01"
  demands:
    - identifier -equals centos8-j17 #It can be any agent pool that has Docker installed, no dependency on java

stages:
  - ${{ if eq(variables['Build.Reason'], 'Manual') }}:
      - template: pipelines/image-publish.yaml@cppAzureDevOpsTemplates
        parameters:
          serviceName: 'framework-stream-error-dashboard'
          RUN_RELEASE: ${{ parameters.RUN_RELEASE }}
