version: '3.8'
services:
  dashboard:
    build: .
    image: stream-error-dashboard:latest
    ports:
      - "8081:80"
    environment:
      - BACKEND_URL=http://host.docker.internal:8080/cakeshop-service
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./main.js:/usr/share/nginx/html/main.js
      - ./api.js:/usr/share/nginx/html/api.js
      - ./ui.js:/usr/share/nginx/html/ui.js
      - ./navigation.js:/usr/share/nginx/html/navigation.js
      - ./filter.js:/usr/share/nginx/html/filter.js 